service: trackdays-alexa-skill

provider:
  name: aws
  runtime: nodejs6.10
  stage: prod
  region: eu-west-1
  profile: trackdaysProdProfile 

package:
  include:
    - ./node_modules/**

functions:
  handler:
    handler: handler.handler
    events:
      - alexaSkill
